// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleLibrarySystem.Data;

namespace SimpleLibrarySystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210411073131_SLS_DB3")]
    partial class SLS_DB3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleLibrarySystem.Data.Tables.Book", b =>
                {
                    b.Property<string>("BookID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("int");

                    b.HasKey("BookID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = "2013-000001",
                            Author = "Sarah J. Mass",
                            ISBN = "9788377478844",
                            Name = "Szklany tron",
                            Publisher = "Uroboros",
                            ReleaseDate = 2013
                        },
                        new
                        {
                            BookID = "2012-000001",
                            Author = "J.R.R. Tolkien",
                            ISBN = "9788324144242",
                            Name = "Drużyna Pierścienia",
                            Publisher = "Amber",
                            ReleaseDate = 2012
                        },
                        new
                        {
                            BookID = "2014-000001",
                            Author = "Andrzej Sapkowski",
                            ISBN = "9788375780635",
                            Name = "Ostatnie życzenie",
                            Publisher = "superNowa",
                            ReleaseDate = 2014
                        });
                });

            modelBuilder.Entity("SimpleLibrarySystem.Data.Tables.Borrowings", b =>
                {
                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BorrowingsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerID", "BookID");

                    b.HasIndex("BookID");

                    b.ToTable("Borrowings");
                });

            modelBuilder.Entity("SimpleLibrarySystem.Data.Tables.Customer", b =>
                {
                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = "0000001",
                            Address = "Jelenia Góra, ul.Kadetów 1",
                            Email = "halajko.tomasz@gmail.com",
                            Name = "Hałajko",
                            PhoneNumber = "883791001",
                            Vorname = "Tomasz"
                        });
                });

            modelBuilder.Entity("SimpleLibrarySystem.Data.Tables.Borrowings", b =>
                {
                    b.HasOne("SimpleLibrarySystem.Data.Tables.Book", "Book")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleLibrarySystem.Data.Tables.Customer", "Customer")
                        .WithMany("Borrowings")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
